### ISSUE TITLE
Fix unclear naming + Better (y/n) handling

### ISSUE THREAD

**Issue by DanyilSomin** [dbiruk/python_learning#2]
```
def stupid_input():
    stupid = input("=====================\n"+
        "Are you stoopid? Do you want to try again(y/n): ")
    if stupid == 'y':
        input_choice()
    else:
        exit()
```
1. I guess if user pressed 'y', he is not stupid, so 'stupid' should be named (for example) notStupid.<br>
2. It is better to ask user again if he pressed the wrong key, and exit only on 'n'.<br>

**Comment by dbiruk** [comment]
fixed in commit https://github.com/dbiruk/python_learning/commit/6c36d979ff149f9d0ff440522c6ab62e109c25f6
@DanyilSomin

**Comment by dbiruk** [comment]
Resolved
