### ISSUE TITLE
Parsing improvement

### ISSUE THREAD

**Issue by DanyilSomin** [dbiruk/python_learning#3]
```
def single_input():
    one_input = (input("Input the operation: "))
    for x in operators:
        if x in one_input:
            vals = one_input.split(x)
            strip_vals = [s.strip() for s in vals]
            strip_vals.append(x)
    calculate(strip_vals[0], strip_vals[1], strip_vals[2])
```

1. Parsing logic is weird. Try parse string into three substrings, then check if operator is valid, then check if operands are valid adn finally pass only correct data to calculate().

**Comment by dbiruk** [comment]
issue addressed in https://github.com/dbiruk/python_learning/commit/379e23261f4bc8dd2fd52d493cf0419fb4236278
